const styles = {
	container: {
		position: "relative",
		padding: "20px",
		textAlign: "center",
	},
	historyContainer: {
		marginTop: "20px",
		height: "200px",
		overflowY: "scroll",
		border: "1px solid #ccc",
		borderRadius: "5px",
	},
	historyList: {
		listStyleType: "none",
		padding: "0",
	},
	historyItem: {
		display: "flex",
		justifyContent: "space-between",
		padding: "10px 0",
		borderBottom: "1px solid #ccc",
	},
	send: {
		color: "red",
	},
	receive: {
		color: "green",
	},
	addButton: {
		position: "fixed",
		bottom: "20px",
		left: "50%",
		transform: "translateX(-50%)",
		backgroundColor: "#4CAF50",
		color: "white",
		fontSize: "24px",
		border: "none",
		borderRadius: "50%",
		width: "60px",
		height: "60px",
		cursor: "pointer",
		zIndex: 10,
	},
	modalBackdrop: {
		position: "fixed",
		top: 0,
		left: 0,
		right: 0,
		bottom: 0,
		backgroundColor: "rgba(0, 0, 0, 0.5)",
		display: "flex",
		justifyContent: "center",
		alignItems: "center",
		zIndex: 10,
	},
	modalContainer: {
		backgroundColor: "white",
		padding: "20px",
		borderRadius: "10px",
		display: "flex",
		flexDirection: "column",
		gap: "10px",
	},
	manualModalContainer: {
		backgroundColor: "white",
		padding: "20px",
		borderRadius: "10px",
		display: "flex",
		flexDirection: "column",
		gap: "15px",
	},
	label: {
		display: "flex",
		flexDirection: "column",
		marginBottom: "10px",
	},
	input: {
		padding: "10px",
		border: "1px solid #ccc",
		borderRadius: "5px",
		marginTop: "5px",
		width: "100%",
	},
	submitButton: {
		padding: "10px",
		backgroundColor: "#4CAF50",
		color: "white",
		border: "none",
		borderRadius: "5px",
		cursor: "pointer",
	},
	confirmationModalContainer: {
		backgroundColor: "white",
		padding: "20px",
		borderRadius: "10px",
		textAlign: "center",
		display: "flex",
		flexDirection: "column",
		gap: "15px",
	},
	confirmButton: {
		padding: "10px",
		backgroundColor: "#4CAF50",
		color: "white",
		border: "none",
		borderRadius: "5px",
		cursor: "pointer",
	},
	cancelButton: {
		padding: "10px",
		backgroundColor: "#f44336",
		color: "white",
		border: "none",
		borderRadius: "5px",
		cursor: "pointer",
	},
	qrModalContainer: {
		backgroundColor: "white",
		padding: "20px",
		borderRadius: "10px",
		display: "flex",
		flexDirection: "column",
		gap: "15px",
		alignItems: "center",
	},
	qrScanner: {
		width: "300px",
		height: "300px",
	},
	modalButton: {
		padding: "10px 20px",
		backgroundColor: "#4CAF50",
		color: "white",
		border: "none",
		borderRadius: "5px",
		cursor: "pointer",
	},
};

export default styles;
