const styles = {
	container: {
		position: "relative",
		padding: "20px",
		textAlign: "center",
	},
	historyContainer: {
		marginTop: "20px",
		height: "200px",
		overflowY: "scroll",
		border: "1px solid #ccc",
		borderRadius: "5px",
	},
	historyList: {
		listStyleType: "none",
		padding: "0",
	},
	historyItem: {
		display: "flex",
		justifyContent: "space-between",
		padding: "10px 0",
		borderBottom: "1px solid #ccc",
	},
	send: {
		color: "red",
	},
	receive: {
		color: "green",
	},
	addButton: {
		position: "fixed",
		bottom: "20px",
		left: "50%",
		transform: "translateX(-50%)",
		backgroundColor: "#4CAF50",
		color: "white",
		fontSize: "24px",
		border: "none",
		borderRadius: "50%",
		width: "60px",
		height: "60px",
		cursor: "pointer",
		zIndex: 10,
	},
	modalBackdrop: {
		position: "fixed",
		top: 0,
		left: 0,
		width: "100%",
		height: "100%",
		backgroundColor: "rgba(0, 0, 0, 0.5)",
		display: "flex",
		justifyContent: "center",
		alignItems: "center",
		zIndex: 1000,
	},
	modalContainer: {
		backgroundColor: "#fff",
		borderRadius: "8px",
		padding: "20px",
		width: "300px",
		boxShadow: "0px 2px 10px rgba(0, 0, 0, 0.1)",
		textAlign: "center",
	},
	manualModalContainer: {
		backgroundColor: "white",
		padding: "20px",
		borderRadius: "10px",
		display: "flex",
		flexDirection: "column",
		gap: "15px",
	},
	label: {
		display: "flex",
		flexDirection: "column",
		marginBottom: "10px",
	},
	input: {
		width: "100%",
		padding: "10px",
		margin: "10px 0",
		borderRadius: "4px",
		border: "1px solid #ccc",
		fontSize: "16px",
	},
	submitButton: {
		padding: "10px",
		backgroundColor: "#4CAF50",
		color: "white",
		border: "none",
		borderRadius: "5px",
		cursor: "pointer",
	},

	confirmationModalBackdrop: {
		position: "fixed",
		top: 0,
		left: 0,
		right: 0,
		bottom: 0,
		backgroundColor: "rgba(0, 0, 0, 0.5)",
		display: "flex",
		justifyContent: "center",
		alignItems: "center",
		zIndex: 100,
	},
	confirmationModalContainer: {
		backgroundColor: "white",
		padding: "20px",
		borderRadius: "10px",
		textAlign: "center",
		display: "flex",
		flexDirection: "column",
		gap: "15px",
	},
	confirmButton: {
		padding: "10px",
		backgroundColor: "#4CAF50",
		color: "white",
		border: "none",
		borderRadius: "5px",
		cursor: "pointer",
	},
	cancelButton: {
		padding: "10px",
		backgroundColor: "#f44336",
		color: "white",
		border: "none",
		borderRadius: "5px",
		cursor: "pointer",
	},
	qrModalContainer: {
		backgroundColor: "white",
		padding: "20px",
		borderRadius: "10px",
		display: "flex",
		flexDirection: "column",
		gap: "15px",
		alignItems: "center",
	},
	qrScanner: {
		width: "300px",
		height: "300px",
	},
	modalButton: {
		width: "100%",
		padding: "10px",
		marginTop: "10px",
		borderRadius: "4px",
		border: "none",
		cursor: "pointer",
		fontSize: "16px",
		backgroundColor: "#007BFF",
		color: "#fff",
	},
	userMenuContainer: {
		position: "fixed",
		bottom: "20px",
		left: "20px",
		zIndex: 1000,
	},
	userIcon: {
		width: "60px",
		height: "60px",
		borderRadius: "50%",
		backgroundColor: "#007BFF",
		display: "flex",
		justifyContent: "center",
		alignItems: "center",
		cursor: "pointer",
	},
	userIconImage: {
		width: "70%",
		height: "70%",
	},
	menu: {
		position: "absolute",
		bottom: "60px",
		left: "0",
		backgroundColor: "#ffffff",
		borderRadius: "8px",
		boxShadow: "0px 2px 10px rgba(0, 0, 0, 0.1)",
		padding: "10px",
		display: "flex",
		flexDirection: "column",
		alignItems: "center",
	},
	menuItem: {
		background: "none",
		border: "none",
		padding: "10px 20px",
		cursor: "pointer",
		width: "100%",
		textAlign: "center",
		borderRadius: "4px",
		margin: "5px 0",
		fontSize: "16px",
		color: "#333",
	},
	menuItemHover: {
		backgroundColor: "#f0f0f0",
	},
	modalButtonCancel: {
		backgroundColor: "#ccc",
	},
};

export default styles;
